### ISSUE TITLE
請問舊版還能用嗎? 新版預計何時上架呢?

### ISSUE THREAD

**Issue by gogobook** [allpay/allPayAIO_Node.js#3]
請問舊版還能用嗎? 新版預計何時上架呢?
會有typescript的版本嗎?

**Comment by AllennChang** [comment]
目前新版本已經在進行測試中, 待測試完成後會立即釋出
typescript的版本目前還沒規劃喔

**Comment by AllennChang** [comment]
已提供新版的SDK囉, 歡迎下載使用
